Не совсем поняла, как в последнем задании оформить выход из цикла. 
Выбивает из него с ошибкой при любом нечисловом значении. 
Пыталась через elif итд, что-то все равно он заходит в цикл проверки числа и вылетает уже там
3;
